### ISSUE TITLE
Open-Falcon plugin for Grafana v4.x支持v4.1.2吗？

### ISSUE THREAD

**Issue by aioloszcy** [masato25/grafana-openfalcon#5]
我在使用时报错
Message:
Cannot read property 'length' of undefined
Stack trace:
TypeError: Cannot read property 'length' of undefined
    at OpenfalconDatasource.query (http://192.168.231.21:3000/public/plugins/grafana-openfalcon-datasource/datasource.js?bust=1490195056438:38:23)
    at b.issueQueries (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:46:4632)
    at b.issueQueries (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:19:2788)
    at g (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:42:13902)
    at http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:42:14074
    at o.$eval (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:42:21715)
    at o.$digest (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:42:20201)
    at http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:42:21802
    at f (http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:40:31995)
    at http://192.168.231.21:3000/public/app/boot.6d63bd8b.js:41:1437

**Comment by masato25** [comment]
支援, 我現在在使用的就是v4.1.2 只是v4的版本是一個特殊的版本他和原本open-falcon的query是不相容的.
它需要使用客製化過的query才可以使用 https://github.com/masato25/open_lambda_query

**Comment by kasimi-rin** [comment]
@masato25 请问上面你说的open_lambda_query要怎么跟grafana-openfalcon-datasource结合使用呢

**Comment by masato25** [comment]
现在 open-falcon/falcon-plus api module裡面已经有自带 grafana api
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/app/controller/graph/graph_routes.go#L28

你可以搭配使用
github.com/open-falcon/grafana-openfalcon-datasource
